spring.application.name=jsp
restclient.productos.baseurl=http://localhost:8080/productos

server.port=8082

#para el post:
# Modo debug si tenemos problemas

## Ver logs detallados de todo el framework
logging.level.org.springframework=DEBUG

## Específicamente para el mapeo de URLs y vistas (muy útil para el 404)
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.view=DEBUG